### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by ItsProfessional** [MightyKnight/ShieldDisruptor#2]

**Comment by Reava** [comment]
bump

**Comment by ItsProfessional** [comment]
> bump

FYI, I've been using another mod called Hide Hands, which is very configurable and you can make it work like shield disrupter

**Comment by MightyKnight** [comment]
Hi, I was finally able to get a version supporting up to 1.20.4 released: https://modrinth.com/mod/shielddisruptor/version/1.7.0

I aim for full multi-version compatibility (one jar, all changes/new features released in all versions) and when I ran into some issues still supporting all versions because of changes in 1.20, I left it first and then kind of forgot about the project.

I believe I tested everything, if you're still going to use ShieldDisruptor and run into any issues, please report them.

Otherwise, Hide Hands does look like a good alternative, even though it is not specifically tailored to shields (ShieldDisruptor should automatically detect all modded shields).

The only problem I have in general with Serilium mods (like HideHands) I've got is that they aren't Open Source licensed.
Though no offense, they are a real mod factory and propably make their money off mods, so I can partially understand keeping them ARR.
